workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
  - Reviewer

Reviewer:
  stage: Reviewer
  tags:
    - {{tags}}
  variables:
    # Secure Files are downloaded to the root directory
    SECURE_FILES_DOWNLOAD_PATH: "/"
    DANGER_GITLAB_API_TOKEN: $GITLAB_TOKEN
    GEMINI_API_KEY: $GEMINI_API_KEY
  before_script:
    - echo "Verifying Node.js and npm versions..."
    - node -v
    - npm -v
    - echo "Downloading Secure Files..."
    # This command downloads the uploaded files (package.json and danger.js)
    # into the path specified by SECURE_FILES_DOWNLOAD_PATH (which is '/')
    - curl --silent "[https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer](https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer)" | bash
    - echo "Installing project dependencies...."
    - npm install
  script:
    - echo "Executing Danger JS code review..."
    - npx danger ci --dangerfile danger.js